### ISSUE TITLE
Add the package back on packagist

### ISSUE THREAD

**Issue by dvaeversted** [fkooman/php-oauth2-client#8]
A shame that this package was removed from packagist.

Could you please add it back again ?

**Comment by fkooman** [comment]
Thanks for your interest in the library! You can add the repository yourself to your `composer.json` as shown here: https://github.com/fkooman/php-oauth2-client#use

The main reason for not wanting my projects available through Packagist is that I feel I need to provide support for them in that case. By just keeping them in my own repository I don't. I'd like the option to delete the library, completely refactor it, move it to another repository, or whatever. I'm slowly moving away from GitHub, so maybe this library will be removed here at some point...

What I recommend you to do is, if you like the library, and feel that it can be useful to your project(s) is to "fork" it and link to your fork from your own code. Then nobody can take it away from you, change it or otherwise break your project. I actually recommend developers do this for all dependencies they use to avoid surprises... In addition, there is a certain risk to use libraries written by one developer... If you are capable to maintain the library yourself (if needed) then go right ahead, it should be easier than with many other OAuth libraries out there that have way more code and a lot more dependencies (that's why I keep it as small/simple as possible!)...

Hope this helps... If you have any questions about the library or OAuth please let me know, happy to help!

**Comment by dvaeversted** [comment]
Thank you for getting back so quickly on this issue.

While i respect your choice, and appreciate the fact that you have chosen to open source your work for us to benefit from.
I am not sure i agree completely with your reasoning, and would cause a set of fragmented/outdated repositories :-)
Atleast i would have prefered just marking the package as abandoned on packagist, so we didn't have to panic fix this in our end.

We chose to use this library over some of the alternatives, due to the low amount of external dependencies that was causing conflicts for some of our consumers of the SDK we are using it in.
For now we have forked the repo, and will consider if we are to replace the dependency completely or start maintaining the fork.

I will close this issue off here, and again thank you for open sourcing this code nonetheless :+1:

**Comment by fkooman** [comment]
>  Atleast i would have prefered just marking the package as abandoned on packagist, so we didn't have to panic fix this in our end.

Yes, this is my bad. I am sorry. I just wasn't aware people were actually using it... it is also hard to see for me... I don't have access to the GitHub and Packagist logs... the indicators available don't necessary say anything, and most are probably my downloads/installs...

You could also see it as a warning that you have to take better care of your dependencies... this could happen to all of them at any time! Wouldn't be the first time it causes big troubles when very popular dependencies disappear all of a sudden. Not sure it happened that much in the PHP community, but the Node community has a number of excellent examples...

> For now we have forked the repo, and will consider if we are to replace the dependency completely or start maintaining the fork.

Great! I feel better now that I am not able to destroy your business anymore by doing strange stuff :-)

> I will close this issue off here, and again thank you for open sourcing this code nonetheless +1

You are welcome! Thanks for staying nice even though it was an inconvenience for you! :+1:
